Login feature
PomianAurelian/SilexProject pull request #22
Opened 2017-08-25 14:20 UTC by PomianAurelian

Fixes #21

2017-09-04 08:58 UTC, ssergiuss commented on database/7-add-user_id-field-to-company-table.sql
> +ALTER TABLE company ADD user_id int(10) DEFAULT NULL;
Use a single statement for operations on the same table, e.g.
```
ALTER TABLE `table_name`
ADD `new_column_1` [...],
ADD `new_column_2` [...];
```

2017-09-04 08:58 UTC, ssergiuss commented on src/Controller/BaseController.php
> + * @author  Pomian Ghe. Aurelian
Use single space between @author and the author name.

2017-09-04 08:58 UTC, ssergiuss commented on src/Controller/BaseController.php
> +     * @return array[]
Return type seems to be incorrect. Also, the function should return an object of type `User`, not an array.

2017-09-04 08:58 UTC, ssergiuss commented on src/Controller/CompanyController.php
>   * Company Controller
When a class extends another use
```
@see ExtendedClass
```
docblock.

2017-09-04 08:58 UTC, ssergiuss commented on src/Controller/CompanyController.php
> +    protected function checkForReview(array $reviews, int $userId)
Use a more suggestive name for the method.
Also, change it so that it will take the company and the user as arguments.

2017-09-04 08:58 UTC, ssergiuss commented on src/Controller/HomeController.php
> +    public function logoutAction(Application $app, Request $request)
Missing docblock.

2017-09-04 08:58 UTC, ssergiuss commented on src/Controller/LoginController.php
> +        echo $_SERVER['REQUEST_URI']; die;
???

2017-09-04 08:58 UTC, ssergiuss commented on src/Controller/LoginController.php
> +            $loginUser = new User();
Do not use a `User` object here, but an array.

2017-09-04 08:58 UTC, ssergiuss commented on src/Controller/LoginController.php
> +            $user = $userRepository->findUser($loginUser->username);
Search for user by both username and password, and do not show specific error messages here like "Invalid password!". The only error message should be something like "Invalid credentials!".

2017-09-04 08:58 UTC, ssergiuss commented on src/Controller/RegisterController.php
> +        if ($user != null) {
Reverse the order of operands. Also, `!==` operator is recommended.

2017-09-04 08:58 UTC, ssergiuss commented on src/Entity/Review.php
> +        $this->review_date = date('Y-m-d H:i:s');
Use the `DateTime` instead of `date` when working with date and times.

2017-09-04 08:58 UTC, ssergiuss commented on src/Entity/User.php
> +     * 1-user | 2-admin
The description for the property should be placed like this
```
@var type Description
```

2017-09-04 08:58 UTC, ssergiuss commented on src/Helper/LoginFormHelper.php
> +        ->add('username', TextType::class, array(
Incorrect indentation.

2017-09-04 08:58 UTC, ssergiuss commented on src/Helper/RegisterFormHelper.php
> +    public function getRegisterForm($app)
Missing docblock.

2017-09-04 08:58 UTC, ssergiuss commented on src/Repository/BaseRepository.php
> +    public function findAll(string $where = null, string $order = null)
Use an `array $criteria` instead of `string $where`.

2017-09-04 08:58 UTC, ssergiuss commented on src/Repository/BaseRepository.php
> +    protected function applyWhere(string $sql, string $order = null)
???

2017-09-04 08:58 UTC, ssergiuss commented on src/Repository/ReviewRepository.php
> +    public function findAllForThisCompanyId(int $id)
You can already do this using `findAll` method and passing the corresponding parameters.

2017-09-04 08:58 UTC, ssergiuss commented on src/Repository/ReviewRepository.php
> +    public function getAverageRatingForThisCompanyId(int $id)
Rename it to `getCompanyAverageRating`. Also, name the argument `$companyId` instead of `$id`.

2017-09-04 08:58 UTC, ssergiuss commented on src/Repository/UserRepository.php
> +    public function findUser(string $username)
Create a generic method `findOneBy` with `array $criteria` as argument that can do this.

2017-09-04 08:58 UTC, ssergiuss commented on src/controllers.php
> +$app->get('/home', "home.controller:indexAction")->bind('homepage');
Use "home" instead of "homepage".

2017-09-04 08:58 UTC, ssergiuss commented on templates/company_layout.html.twig
>  <!DOCTYPE html>
Do you need a new layout for company related pages?

2017-09-04 08:58 UTC, ssergiuss commented on templates/form/login_form.html.twig
> +    Login Page
Use "Login" instead of "Login Page".

2017-09-04 08:58 UTC, ssergiuss commented on templates/form/login_form.html.twig
> +{% block scripts %}
You can remove the `scripts` block if there is nothing inside.

2017-09-04 08:58 UTC, ssergiuss commented on templates/home/index.html.twig
> +    Silex Project Homepage
Use just "Home".

2017-09-04 08:58 UTC, ssergiuss commented on templates/home/index.html.twig
> +        {% if user.privilege > 1 %}
Use specific values when checking the privilege.

2017-09-04 08:58 UTC, ssergiuss commented on web/index_dev.php
> +
Remove the extra line.

2017-09-04 09:26 UTC, PomianAurelian commented on database/7-add-user_id-field-to-company-table.sql
> +ALTER TABLE company ADD user_id int(10) DEFAULT NULL;
✓

2017-09-04 09:26 UTC, PomianAurelian commented on src/Controller/BaseController.php
> + * @author  Pomian Ghe. Aurelian
✓

2017-09-04 09:28 UTC, PomianAurelian commented on src/Controller/CompanyController.php
>   * Company Controller
✓

2017-09-04 09:28 UTC, PomianAurelian commented on src/Controller/HomeController.php
> +    public function logoutAction(Application $app, Request $request)
✓

2017-09-04 09:29 UTC, PomianAurelian commented on src/Controller/LoginController.php
> +        echo $_SERVER['REQUEST_URI']; die;
✓

2017-09-04 09:30 UTC, PomianAurelian commented on src/Controller/RegisterController.php
> +        if ($user != null) {
✓

2017-09-04 09:32 UTC, PomianAurelian commented on src/Controller/LoginController.php
> +            $user = $userRepository->findUser($loginUser->username);
✓

2017-09-04 09:39 UTC, PomianAurelian commented on src/Entity/Review.php
> +        $this->review_date = date('Y-m-d H:i:s');
✓

2017-09-04 09:39 UTC, PomianAurelian commented on src/Entity/User.php
> +     * 1-user | 2-admin
✓

2017-09-04 09:51 UTC, PomianAurelian commented on src/Helper/LoginFormHelper.php
> +        ->add('username', TextType::class, array(
✓

2017-09-04 09:57 UTC, PomianAurelian commented on src/Helper/RegisterFormHelper.php
> +    public function getRegisterForm($app)
✓

2017-09-04 10:03 UTC, PomianAurelian commented on src/Repository/ReviewRepository.php
> +    public function getAverageRatingForThisCompanyId(int $id)
✓

2017-09-04 10:04 UTC, PomianAurelian commented on src/controllers.php
> +$app->get('/home', "home.controller:indexAction")->bind('homepage');
✓

2017-09-04 10:04 UTC, PomianAurelian commented on templates/form/login_form.html.twig
> +    Login Page
✓

2017-09-04 10:04 UTC, PomianAurelian commented on templates/home/index.html.twig
> +    Silex Project Homepage
✓

2017-09-04 10:06 UTC, PomianAurelian commented on templates/home/index.html.twig
> +        {% if user.privilege > 1 %}
✓

2017-09-04 10:06 UTC, PomianAurelian commented on web/index_dev.php
> +
✓

2017-09-04 10:18 UTC, PomianAurelian commented on src/Controller/LoginController.php
> +            $loginUser = new User();
✓

2017-09-04 12:37 UTC, PomianAurelian commented on src/Repository/ReviewRepository.php
> +    public function findAllForThisCompanyId(int $id)
✓

2017-09-04 13:00 UTC, PomianAurelian commented on templates/company_layout.html.twig
>  <!DOCTYPE html>
✓

2017-09-04 14:56 UTC, PomianAurelian commented on src/Controller/BaseController.php
> +     * @return array[]
✓

2017-09-04 14:56 UTC, PomianAurelian commented on src/Repository/BaseRepository.php
> +    public function findAll(string $where = null, string $order = null)
✓

2017-09-04 14:56 UTC, PomianAurelian commented on src/Repository/BaseRepository.php
> +    protected function applyWhere(string $sql, string $order = null)
✓

2017-09-04 14:56 UTC, PomianAurelian commented on src/Repository/UserRepository.php
> +    public function findUser(string $username)
✓

2017-09-04 14:56 UTC, PomianAurelian commented on templates/form/login_form.html.twig
> +{% block scripts %}
✓

2017-09-04 15:29 UTC, PomianAurelian commented on src/Controller/CompanyController.php
> +    protected function checkForReview(array $reviews, int $userId)
✓

2017-09-05 08:10 UTC, ssergiuss requested changes

2017-09-05 08:10 UTC, ssergiuss commented on src/Controller/BaseController.php
> +        if (null !== $aux){
Space between `)` and `{`.

2017-09-05 08:10 UTC, ssergiuss commented on src/Controller/CompanyController.php
> +        $companyCriteria['id'] = $id;
Initialize variable before use:
```
$companyCriteria = [];
```

2017-09-05 08:10 UTC, ssergiuss commented on src/Controller/CompanyController.php
> +        $company = $companyRepository->findOneBy($companyCriteria);
Use
```
$companyRepository->findOneBy(['id' => $id]);
```
instead.

2017-09-05 08:10 UTC, ssergiuss commented on src/Controller/CompanyController.php
> +        $reviews = $reviewRepository->findBy($reviewCriteria, null);
Do not pass `null` as param (unnecessary).

2017-09-05 08:10 UTC, ssergiuss commented on src/Controller/CompanyController.php
> +                    $company->user_id = $user['id'];
Use `$user->id` instead.

2017-09-05 08:10 UTC, ssergiuss commented on src/Entity/User.php
> +     *
Remove empty line.

2017-09-05 08:10 UTC, ssergiuss commented on src/Entity/User.php
> +     * @var int 1-user | 2-admin | 3-super admin
Use class constants for user privileges.

2017-09-05 08:10 UTC, ssergiuss commented on src/Repository/BaseRepository.php
> +        if (null !== $criteria) {
Move all block into `applyCriteria` method.

2017-09-05 08:10 UTC, ssergiuss commented on src/Repository/BaseRepository.php
>          $sql = "SELECT * FROM " . $this->getTableName();
Create new method `getBaseSelect`.

2017-09-05 08:10 UTC, ssergiuss commented on src/Repository/BaseRepository.php
> +        foreach ($criteria as $key => $value) {
Use PHP `implode` function.

2017-09-05 08:10 UTC, ssergiuss commented on src/Repository/UserRepository.php
> +    public function findUser(string $username)
Remove method `findUser`.

2017-09-05 09:22 UTC, merged